# Site settings
title: Lens by HTML5 UP | Jekyll automation by mwilczek-net.github.io
name: Lens template with Jekyll
description: Lens template build powerred with Jekyll engine
defaultSocialMediaImage:

socialMedia:
  Twitter:
    url: "#"
    icon: "brands fa-twitter"
  Instagram:
    url: "#"
    icon: "brands fa-instagram"
  GitHub:
    url: "https://mwilczek-net.github.io/"
    icon: "brands fa-github"
  Email:
    url: "#"
    icon: "fa-envelope"
  Web:
    url: "http://mwilczek.net"
    icon: "solid fa-globe"


images:

# Build settings
markdown: kramdown

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all

# Host domain
url: "https://mwilczek-net.github.io"

# URL from domain root
baseurl: "/lens-on-jekyll"
